### ISSUE TITLE
[tr064] Add support to backup of FRITZ!Box

### ISSUE THREAD

**Issue by cweitkamp** [smarthomej/addons#133]
I have a monthly task which I would like to automate. Create a backup of my FRITZ!Box.

According to [TR-064 Support – DeviceConfig](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/deviceconfigSCPD.pdf) there is a SOAP call `X_AVM-DE_GetConfigFile` to provide a password encrypted backup file to be downloaded at the given (output of the SOAP call) URL.

It would be really great to add support for this into the binding (e.g. Channel or ThingAction). Can you help me?

If I run the backup manually the resulting file is called like this: "FRITZ.Box 7590 154.07.27_17.06.21_0956.export". Looks like the following pattern: "`<MODEL> 154.<FRITZ!OS_VERSION>_<DD.MM.YY_HHmm>.export`" (Currently I have no idea about the meaning of the "154").

**Comment by J-N-K** [comment]
Since we need an input don't want to poll that within the cycle we ususally do, I think that a thing action would be the best choice.  I think we should retrieve the data instead of the URL since the documentation says the URL provided by the SOAP action is protected with digest authentication and is valid only for 30s.

The question is what the best datatype for the return value is. We could either use a hex encoded string or a byte array. WDYT?

**Comment by cweitkamp** [comment]
A `ThingAction` sounds like the better choice. But we do not (really) need an input parameter for it. We can pick the password from Thing configuration.

If you want to return something a `byte[]` sounds good. It can be easily written to disc via `Files.write()`. Otherwise I suggest to store the backup file directly (e.g. to `$OPENHAB_CONF/backup` or a binding specific path) end return the local path.

**Comment by J-N-K** [comment]
Unfortunately it's not so easy. I just tried and it seems that at least newer firmware versions require 2FA for the config backup:

```
HTTP-Response-Code 500 (Internal Server Error), SOAP-Fault: 866 (second factor authentication required)
```

**Comment by cweitkamp** [comment]
Okay, I see 😞 .

There is a [X_Auth service](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/x_auth.pdf) which could help. AFAIR I had to dial a code on a connected DECT phone last time. Maybe there is a way to simulator this procedure.

If you cannot get it working soon it die not hurt much. If I can help you in any way let me know, share your code, whatever.
