### ISSUE TITLE
[amazonechocontrol] lastVoiceCommand does not work

### ISSUE THREAD

**Issue by rogrun** [smarthomej/addons#178]
The channel  `lastVoiceCommand` does not work. When I say something, Alexa hear the command, but the Channel does not receive it. There is no error in log. 

Binding version: 3.2.4
Tested on OH Version: 3.2 and 3.1

**Comment by J-N-K** [comment]
I just checked it work for me. So this is most probably not a general issue. Can you check if commands are working? If you link an item to the `volume` channel, do you get a value and does it change if you say "Alexa, lauter"?

**Comment by rogrun** [comment]
I've checked, the value does not change. Do you have any idea whats wrong on my site?

**Comment by J-N-K** [comment]
Yes. The websocket connection died or could not be established. This was probably fixed with #170. I'll release a new version as soon as #176 has been merged.

**Comment by rogrun** [comment]
Thanks. So it's a bug and I don't have to search on my site. :)

**Comment by rogrun** [comment]
Since the new release everything work fine.
