### ISSUE TITLE
[telenot] Connection without serial bridge

### ISSUE THREAD

**Issue by laserir** [smarthomej/addons#184]
Hi there! I can connect to the telenot device using the BuildSec App. It has a static IP in my home network.

my question would be… is it possible to connect without the use of a serial cable?

**Comment by rogrun** [comment]
No it is not possible. Telenot did not open this connection. So you can only connect via the GMS port.

**Comment by laserir** [comment]
What a shame ;) Thanks for relying so fast.
I may consider doing so. Is it correct that there is no password or token to pass? Is it possible to arm/disarm the system?

**Comment by rogrun** [comment]
Yes that's right. You need no token or password. Only the GMS Port has to be enabled in the CompasX Software and connected via a serial ip interface. But be carefull, you can arm/disarm with the binding. So everyone who has access to your network can control your alarm system.

**Comment by laserir** [comment]
I see… I think I‘ll stick with distinct inputs for the commands. Thanks a lot anyways!!
