### ISSUE TITLE
Profile to extract specific bits from DecimalType

### ISSUE THREAD

**Issue by tarag** [smarthomej/addons#227]
There are several channel profiles to work with numbers but I don't think I can perform the following task, extract one (to a Contact Item) or several (to a Number Item) bits from a number type KNX thing (in that situation an integer datapoint of varied length). There are this kind of group objects in ABB range for example to return the status of an actuator.

Do you have any idea how to achieve this or do you think this could be implemented ?

**Comment by J-N-K** [comment]
I think the easiest way is using a JS transformation. You can use something like 

```
(function(i) {
    return (i & 0x02) ? 1 : 0;
})(input)
```

to extract a single bit to 1/0. This does not fully solve your issue, though because it can't convert to OPEN/CLOSED or ON/OFF. What type of DPT is the actor using?

**Comment by tarag** [comment]
Thanks for the idea, that a start. Indeed if I am still left with a Number it's not great, I'll try to see what this means. The DPT type of the source is 20.001, 1 byte bitset.

**Comment by J-N-K** [comment]
I thought about this a bit more. It's easy for the direction binding -> item, but the other direction is very difficult. Of course setting the bit from the mask is not an issue, but we would need to store the other bits to get the correct bitset and that will go wrong if the first update is done from openHAB side (before the current state is received from the bus).

**Comment by tarag** [comment]
Thanks for taking some more time. But in fact these statuses are most of the time read only so binding -> item is the only direction that matters for the moment. 

The goal was rather to avoid writing a transformation js for each relevant bit/set of bits of the bitfield.

**Comment by J-N-K** [comment]
I'm currently enhancing the math profile so that you can use bitwise operations. There is one drawback to that: if you want to extract bit 4 (0x08), you'll get 0 or 8 as result. Would that help?

**Comment by cweitkamp** [comment]
Solved by #246. Isn't it?
