### ISSUE TITLE
How to install the amazonecho on 3.2RC1

### ISSUE THREAD

**Issue by jimtng** [smarthomej/addons#247]
Hi, I'm trying to install the smarthome/j version of amazonecho binding onto my 3.2rc1. I tried building the jar from source and I have placed both the org.smarthomej.commons-3.1.9-SNAPSHOT-sources.jar and org.smarthomej.binding.amazonechocontrol-3.1.9-SNAPSHOT.jar into my addons folder but it doesn't work.

```
11:54:31.926 [WARN ] [org.apache.felix.fileinstall         ] - Error while starting bundle: file:/openhab/addons/org.smarthomej.binding.amazonechocontrol-3.1.9-SNAPSHOT.jar
org.osgi.framework.BundleException: Could not resolve module: org.smarthomej.binding.amazonechocontrol [234]
  Unresolved requirement: Import-Package: org.smarthomej.commons; version="[3.1.9,3.2.0)"
```

Where should I put the commons jar?

**Comment by jimtng** [comment]
Oops I've just realised I've built / installed the wrong version. I needed to check out the 3.2.x branch.

**Comment by jimtng** [comment]
It works using the 3.2.x branch!

**Comment by J-N-K** [comment]
On OH 3.2 (not RC1, it had a bug in that function), you can also use the JSON 3rd party marketplace by adding `https://download.smarthomej.org/addons.json` as URL. Make sure you removed the files from the addons folder before you install from UI.

**Comment by jimtng** [comment]
Thanks for the tip on json marketplace. Can this be set up using text config (addons.cfg?) and can I also install the addon using addons.cfg?

**Comment by J-N-K** [comment]
No, I don't think that's possible. It works like the Community Marketplace, just with another addon source.

**Comment by jimtng** [comment]
I tried the json method, and tried installing the amazonecho binding via GUI but it just keeps twirling, never completed. I've since removed the json and just copied the jar into the addons folder.

**Comment by J-N-K** [comment]
If you are on RC1 this is expected due to a bug (which has been fixed for the release version).
