### ISSUE TITLE
Explain how updates are installed in Readme.md

### ISSUE THREAD

**Issue by Flole998** [smarthomej/addons#261]
While there are installation instructions I haven't found any information on how updates will be installed when a new version of an addon is released (assuming I installed the repository as described in the Readme.md). I assume that openHAB is checking automatically periodically for new releases and installs them automatically? Or do I need to do something manually? Maybe a FAQ would be great that covers this.

**Comment by J-N-K** [comment]
Good point. I'll add a section to the readme about updating.
