### ISSUE TITLE
[tuya] not discovering ip address

### ISSUE THREAD

**Issue by jimtng** [smarthomej/addons#324]
I tried adding several of my tuya devices then started a trace log. It seems that 2 of my devices continuously do udp broadcast, readily advertising their ip addresses. The others don't seem to be doing much. Out of the 2 that I added, 1 finally figured out its ip address after a long time, and 1 is still in CONFIG_PENDING Waiting for IP Address state.

**Comment by jimtng** [comment]
Update: it seems that I cannot run tuya-mqtt at the same time. As soon as tuya-mqtt is stopped, the binding received udp broadcast with the ip address of the device that was pending.

**Comment by J-N-K** [comment]
Yes, only one local connection is possible. Maybe that should be added to the documentation.
