### ISSUE TITLE
[tuya] thing removal is stuck

### ISSUE THREAD

**Issue by jimtng** [smarthomej/addons#327]
When removing a discovered tuya thing, it is stuck at "REMOVING" status. I had to force remove it.

Using Openhab  3.3.0-SNAPSHOT - Build #2762

**Comment by J-N-K** [comment]
Can you explain a little bit more what you did? I assume you added a thing in the UI (discovery or manually?) Then you tried to delete the thing. Was the binding installed when that happened?

**Comment by jimtng** [comment]
I added a Tuya Cloud Project in the UI, then added a discovered device (e.g. a light bulb). It is that discovered device (the lightbulb) that I tried to remove and it got stuck. It was all via UI, no textual config.

**Comment by J-N-K** [comment]
But the binding was still installed?

**Comment by jimtng** [comment]
Yes the binding is still installed. The cloud project is still online during the removal.

**Comment by J-N-K** [comment]
I tried that more than dozen times now and could not reproduce it. Do you have that issue all the time or did it happen once?

**Comment by jimtng** [comment]
I haven't been able to reproduce it. I'll close this issue and reopen it if needed. Thanks for checking on your end too.

**Comment by jimtng** [comment]
The thing stuck at removal happens when the thing is disabled.

Steps:

- Add a tuya thing
- Set it to disabled
- Remove the thing

**Comment by J-N-K** [comment]
Ah. That's a known issue in openHAB core: https://github.com/openhab/openhab-core/issues/2517
