### ISSUE TITLE
[INFO ] [community.CommunityKarafAddonHandler] - Reinstalling missing marketplace KAR: json:org-smarthome-binding-tuya-develop

### ISSUE THREAD

**Issue by BigGeorgeTx** [smarthomej/addons#350]
Whenever I restart openHAB, I see this in the log:
`2022-03-21 13:33:08.957 [INFO ] [community.CommunityKarafAddonHandler] - Reinstalling missing marketplace KAR: json:org-smarthome-binding-tuya-develop`

I suspect that early on I missed the important step of removing the binding before a certain upgrade.  It doesn't seem to affect anything (that I know of).  But I have no idea how to get rid of it.

Any suggestions?

**Comment by J-N-K** [comment]
Is this happening once or more often? Did you clean cache before? This is just the message that the bundle is needed, but currently not installed.

**Comment by BigGeorgeTx** [comment]
Today I upgrade one of my installations to 3.3.0M3 using openhabian.  When openHAB first restarted, I received this message, and none of the bindings started except for the smarthome/j tuya and amazonecho control bindings that I am using.  I stopped openHAB using openhab-cli stop, cleared the cache also with openhab-cli.  When I tried to start with openhab-cli start, it said that there was already a openhab.service configured and to use systemctl start.  I did, and got the same message (missing ...), and the bindings didn't load.  I did a systemctl restart openhab, and it started, without the "missing ..." error message, and all of the bindings loaded and, knock on wood, everything seems to be working.

Should I also update the smarthome/j bindings?  I'm currently using the develop versions of both from M2.  They seem to be  working OK.  But it would be nice to git rid of the extra log information that was created to assist in troubleshooting.

**Comment by J-N-K** [comment]
Yes, just switch to the 3.2.12 release, it's code-wise the same as the develop version without the logging.

**Comment by BigGeorgeTx** [comment]
I upgraded one of my installations to 3.3.0M7 today.  The first time it started, I had these messages in the log, which appear related to this earlier issue.

`2022-06-20 18:02:50.900 [INFO ] [community.CommunityKarafAddonHandler] - Reinstalling missing marketplace KAR: json:org-smarthome-binding-tuya-develop
2022-06-20 18:02:51.694 [INFO ] [rketplace.MarketplaceBundleInstaller] - Reinstalling missing marketplace bundle: marketplace:104494`

As before, the second restart yielded the same message for the smarthome/j amazonechocontrol binding.

After the 3rd restart of openhab, both the tuya and amazonechocontrol smarthome/j bindings appear to be working as expected.

**Comment by J-N-K** [comment]
That‘s pretty normal and works as designed if you upgraded your installation. 

The reason is that the addon is marked as installed (like any other addon) but it was removed during upgrade. That’s why it is re-installed. The same happens for all other addons, it‘s just not logged (or to be precise, I believe it is logged as DEBUG level, so you don’t see it).
