### ISSUE TITLE
Installed Smarthome/J bindings not displayed in UI but are working

### ISSUE THREAD

**Issue by BigGeorgeTx** [smarthomej/addons#364]
When I look at the list of bindings in the openHAB UI, the installed, running and functioning Smarthome/J bindings that I'm using (Tuya and AmazonEchoControl) do not appear on the list of Other Add-ons.  13 other Smarthome/J bindings are there.  This was happening in openHAB 3.3.0M3.  I tried updating to M5.  The first time it loaded I saw the same warning in the log reported with my other install (https://github.com/smarthomej/addons/issues/350).  I cleaned the cache and restarted.  No more warning, but it is not listed in the UI.

I checked the /var/lib/openhab/kar ... folder and an older version (3.2.11 of the Tuya binding) is there.  I would like to update to the 3.2.12 which fixed issues I have encountered on my other install.

Should I back up my configuration, remove openHAB completely, make a clean install and then restore my back up?  Or is whatever gremlin I'm facing likely to be included in the config files, or is there a better way?

Thanks.

**Comment by J-N-K** [comment]
Can you please go to the Karaf-console and show `feature:repo-list` as well as the content of `/var/lib/openhab/jsondb/org.openhab.jsonaddonservice.json`? Thanks.

**Comment by J-N-K** [comment]
This is a bug in openhab-core. A PR to fix it has been submitted. In the mean-time you can go to Settings/Add-on Management and enable "Show potentially incompatible Add-ons". The installed add-ons should show up and you can uninstall them. After that you can disable the setting once again.

**Comment by BigGeorgeTx** [comment]
Thanks.  I did as you suggested and it worked.

If you still want me to get the information you requested earlier, let me know and I will do it.  I was traveling and didn't get to it earlier.  Since you have figured it out, I'm assuming you don't need it any more, but I'm happy to provide it if it will help.
