### ISSUE TITLE
Can't receive nor send any results for IR device (BlitzWolf BW-RC1)

### ISSUE THREAD

**Issue by pedlima** [smarthomej/addons#376]
Hi,

First of all, great work here! Congrats and thank you for this.

I'm wondering how this could work locally.

In the past when this came with ESP chip I flashed with Tasmota, but now that they do not work with those chips anymore, I was trying to find another solution to work with Tuya devices without having to rely on an internet connection and being able to control it only locally.

I couldn't find anything mentioning IR devices so I can only imagine that it is still not supported, but this could be a very important addon.

Best regards,
Pedro Lima

**Comment by J-N-K** [comment]
How are these devices connected? Are they discovered by the discovery function after you created the project?

**Comment by pedlima** [comment]
> How are these devices connected? Are they discovered by the discovery function after you created the project?

It's connected via wifi and yes, they were automatically discovered after I created the project in iot.tuya.com

The thing is, I suspect that I cannot do as I do with Tasmota, that I can access the code when I click on a remote key and then replicate that code. In this case it seems I can only use the Tuya APP functionalities so it means I always have to first setup the remote keys I want via APP, then maybe interacting with the cloud item and send information to what I want to do. But even that, I could not do and even if I could, it means I would always be using the Tuya cloud anyway which is not what I wanted since it is not offline.

Is there a way to eventually solve this case?

**Comment by J-N-K** [comment]
Don't know. I don't have any of these devices and that makes it hard to find out what is missing. What channels do you see?

**Comment by J-N-K** [comment]
@pedlima Can you comment on my last question?

**Comment by pedlima** [comment]
> @pedlima Can you comment on my last question?

Yes, sorry.

Here are the channels for the binding I created:
![channels](https://user-images.githubusercontent.com/27860888/180274917-595d74a5-c0bf-401b-9c63-5f987620a7d1.jpg)

I tried with 3.3 and 3.1 protocols and if I use Tuya Smart APP, the remote for the AC works perfectly. But this simple ON and OFF, do not work as well as any of the other channels that I've tried.

I would suppose that something as simple as ON and OFF would work out of the box, right?

Also, what happens if eventually Tuya cloud goes offline, I lose the hability to control the equipment, right?

**Comment by J-N-K** [comment]
The Tuya Binding is not affected by cloud offline as it uses local access only. The cloud is only required for discovery. What is the `productId` of this device?

Is there a power-switch in the App and that works?

**Comment by pedlima** [comment]
> The Tuya Binding is not affected by cloud offline as it uses local access only. The cloud is only required for discovery.

Awesome, that's good to know! :)

> What is the `productId` of this device?

This is it: zjqwdftbog2dnkhc

> Is there a power-switch in the App and that works?

Yes.

EDIT: @J-N-K corrected productId, the previous one was incorrect. But why do you need the productId?

**Comment by pedlima** [comment]
@J-N-K any news on this?

**Comment by J-N-K** [comment]
I have ordered one for testing.

**Comment by pedlima** [comment]
> I have ordered one for testing.

Oh, cool! I could have sent you one of the 3 I have here, since you are helping with this, it would be the least I could do and it would probably be faster than ordering it. :D

Let's hope you can figure that out. :)

**Comment by J-N-K** [comment]
Hahaha. My order was cancelled today, because "there is no shipping company available that can ship this article to you". Of course, DHL will NEVER, EVER ship a small electronics part to Germany's 25th largest city.

I have ordered from another company.

**Comment by pedlima** [comment]
> My order was cancelled today, because "there is no shipping company available that can ship this article to you".

Yup, this excuse is, at least, hilarious!

I mean, I live in a very, very tiny country side rural area and had NEVER one single order canceled due to that reason.

And they tell you that, living on a big city. 😄 

At least they should try to be a little bit more creative on their weird excuses. Ahahha.

Good luck with the new order and if you want, I can ship one unit for you, no problem. ;)

**Comment by J-N-K** [comment]
It's difficult.

For each (remote controlled) device that you create in the app a "virtual device" is created. This is then used for cloud control. After disabling internet access, I can still locally control the device, but only that device. Somehow the app figures out which codes need to be send and uses those. However, they are not cached, if you leave the device in the app, you can't control it afterwards. I didn't figure out yet how these codes are retrieved.

**Comment by J-N-K** [comment]
What devices are you trying to control (type/brand/model)? Do you use the Tuya Smart or the SmartLife app?

**Comment by pedlima** [comment]
First, let me thank you once again for your time invested on this subject.

> What devices are you trying to control (type/brand/model)? Do you use the Tuya Smart or the SmartLife app?

I have an AC Samsung ([this one](https://www.samsung.com/de/support/model/AJ026TN1DKG/EU/)) and I use Tuya Smart APP.

**Comment by J-N-K** [comment]
There is some progress, don‘t close.

**Comment by pedlima** [comment]
> There is some progress, don‘t close.

Interesting news. What have you been able to accomplish so far?

**Comment by J-N-K** [comment]
Someone found at least parts of what is needed to encode the correct commands, so we may be able to determine the correct codes from tables in the internet.

**Comment by pedlima** [comment]
That's great, where did you found that?

I ended up buying [some of these](https://www.aliexpress.com/item/1005004668913469.html?spm=a2g0o.order_list.0.0.52871802J56lfa) and put Tasmota on it. Works like a charm!

**Comment by J-N-K** [comment]
It's here: https://github.com/jasonacox/tinytuya/issues/74
