### ISSUE TITLE
Support for Tuya Cloud Device

### ISSUE THREAD

**Issue by palaslet** [smarthomej/addons#389]
Some Tuya devices does not accept direct network connection. These are in particular extreme low power devices such as  battery powered temperature sensors etc. These devices wake up based on an interval (my particular device wakes up once every hour), and posts their status to the cloud and/or retrieves commands from the cloud.

Such devices maybe configured as a TuyaCloudDevice thing, or maybe TuyaDevice can fall back to cloud api calls if direct connection fails, so that the binding can use the cloud api to retreive status and post commands.

I do not have enough java experience to implement such solution myself, but from the logs in openhab it seems the binding is already retrieving this information during the discovery call.

**Comment by 0verEngineer** [comment]
Hey, this is still an issue.

**Comment by dieterkoller** [comment]
Hi, I would also like to have that issue solved. I have a couple of battery driven Tuya-WiFi temperature and humidity sensors (with and w/out display) that update their readings to the tuya cloud only once per hour. The only relevant information I've found so far is [https://www.elektroda.com/rtvforum/topic3968377.html]. But that is beyond my scope.

**Comment by J-N-K** [comment]
I tried it and didn't manage to get a stable solution. I still have the code, so if anyone wants to try, I can show what I already have.
