### ISSUE TITLE
[Tuya] Unable to logon

### ISSUE THREAD

**Issue by BasvanH** [smarthomej/addons#404]
Hello,

I'm not able to add my devices in the iot Tuya portal. When I scan the QR in the app I authorize it, the webpage detects it's scanned but does not show any devices to be imported.

Secondly, in Openhab the Tuya binding wont authenticate. I have my doubts regarding the App username. Is it the email address I used to register? In the app when you go to your profile you can adjust your display name, but the app makes it look like you are changing your logon name. I used my email adres and the display name as username in the Tuya binding bot still cant authenticate.

The binding logs the following when I try to authenticate:
```
2022-10-14 17:33:42.185 [WARN ] [ding.tuya.internal.cloud.TuyaOpenAPI] - Request failed: Result{timestamp=1665761622182, code=1106, msg=permission deny, success=false, result=null}, no token received
```

I hope someone can help me getting it to work.

Thanks!
Bastiaan

**Comment by BasvanH** [comment]
Got it, apparently the Netherlands datacenter is central Europe not Western Europe.

**Comment by J-N-K** [comment]
Yes, that‘s very confusing sometimes.
