### ISSUE TITLE
Smarthome/J Java Rule Automation documentation

### ISSUE THREAD

**Issue by clinique** [smarthomej/addons#405]
I'm having a hard setting up my file structure between rules classes (works fine under jsr223 folder) and personal libraries (located I suppose under /lib/java.

Would you be kind enough to extend a bit documentation with an example of file/folder tree ?

Thanks a lot.

**Comment by J-N-K** [comment]
Something like

```
automation
  jsr223
    java
      org
        smarthomej
          automation
            javarule
              BedroomRules.java
  lib
    core-dependency.jar
    javarule-dependency.jar
    java
      org
        smarthomej
          automation
            javarule
              PersonalRuleUtil.java
```

**Comment by clinique** [comment]
Perfect
