### ISSUE TITLE
Are the notifications from tuya door sensors and battery operated devices received locally?

### ISSUE THREAD

**Issue by rlarranaga** [smarthomej/addons#409]
I have been thinking about getting some tuya door sensors to test. i am currently also testing the smarthomej/tuya binding. 

Are the notification from sensors received locally, or are they received through the cloud? In other words, do i loose notifications from sensors i(battery operated devices)f i loose internet connectivity?

Thanks

**Comment by J-N-K** [comment]
I don't own battery operated devices, so I'm not sure they send values. But the cloud is only used for discovery, not for values. So if it works at all, then it'll also work without internet connection.

**Comment by rlarranaga** [comment]
Yeah, i would lean to "Not working at all" unless it is in polling mode, but that kind of defeats the purpose of a battery operated sensor.

All the ones I have seen advertise push notifications to the app, but for them to do local notifications they would either have to do them to a broadcast/multicast address (Not the most secure), or they would have to have a configuration for a local host....
