### ISSUE TITLE
IR Smart Remote Channel

### ISSUE THREAD

**Issue by TikaToka** [smarthomej/addons#424]
I Tried to solve it by https://github.com/jasonacox/tinytuya/issues/74#issuecomment-1139730159
So I made String Channel name send_ir and set as below

![image](https://user-images.githubusercontent.com/49054667/204842196-fadd0313-4183-48a9-a319-b732ee6381a0.png)

However, It does not work as I thought, I thing it does not send this values to IR device but do nothing.

Is there a perfect solution for IR smart device?

Mine is Tuya S06 Universal Wifi IR Remote

**Comment by J-N-K** [comment]
No, unfortunately this is still work in progress.

**Comment by d51x** [comment]
i made PR for IR Smart Remote Channel
https://github.com/smarthomej/addons/pull/471
