### ISSUE TITLE
updated to openHAB 4.0.0 Build #3266 Tuya wont work anymore

### ISSUE THREAD

**Issue by xsasx** [smarthomej/addons#445]
Sadly my docker updated yesterday to openHAB 4.0.0
Build #3266 now your great Tuya Addin isnt work anymore whta i must do to get it back to work ?

**Comment by J-N-K** [comment]
Currently openHAB 4 is not supported. There is ongoing work, but we only have untested snapshots available.

**Comment by xsasx** [comment]
thanks for the fast answer - damn ok - if you have anything to test i will stand by :)
