### ISSUE TITLE
openHAB Installation problem

### ISSUE THREAD

**Issue by seb8282** [smarthomej/addons#452]
Hi,
I've installed your plugin and got it working once (I only tried cloud connection to Tuya so far). Then the next day I got only the error "HANDLER_MISSING_ERROR" and "Handler factory not found". Also removing and re-installing does not help. While installing a lot of failures occur. I've attached the log file. Can you help me what I did wrong?
Thank you very much!
[openhab.log.txt](https://github.com/smarthomej/addons/files/10544352/openhab.log.txt)

**Comment by seb8282** [comment]
I've also set up an entirely new openHAB container and config. I've added only a Shelly binding for testing and then installed the Tuya addon. Same result as in the old system...

**Comment by J-N-K** [comment]
`Caused by: java.net.BindException: Address already in use`

Something else is already listening on port 6666 or 6667.
