### ISSUE TITLE
Tuya things and items are online but do not work (OH3.4.1.  on raspi4)

### ISSUE THREAD

**Issue by LuxMcDiver** [smarthomej/addons#454]
Hi,

I have installed the Tuya Cloud Project as a Thing and added 3 more autodiscovered Things (Zigbee Gateway, Switch and dimmer).
All things and items are Online, but the devices do not react. I see nothing in the Log Viewer.

Any idea what is wrong?

Regards

Nico

**Comment by J-N-K** [comment]
The "old" things still work? Please use `log:set TRACE org.smarthomej.binding.tuya` on the karaf console and see if you get any suspicious logs. You can disable logging with `log:set INFO org.smarthomej.binding.tuya`.

**Comment by andredts** [comment]
I have the same setup as Nico, but I also have wifi devices and they work perfectly; my Zigbee devices on the other hand only show online and I can read the status (If I click the switch it changes in Openhab, but I dosen't respond to commands sent from Openhab) Could it be a problem with the command channel having to pass through the Zigbee gateway?
