### ISSUE TITLE
[Viessmann] missing basic-API-values

### ISSUE THREAD

**Issue by LukaNoah** [smarthomej/addons#465]
Hi,

I'm missing the following basic-api-values in the binding with my VitoDens 222-F:

**heating.boiler.temperature**       Shows the set target temperature value of the boiler
**heating.dhw.charging**      Shows whether the hot water charging for the DHW storage is currently active
**heating.dhw.temperature.hysteresis**      Shows the hysteresis value of the Domestic Hot Water temperature in heat pumps. Also provides the command to set it
**heating.circuits.N.temperature**      Shows the value of the target temperature for circuit N
**heating.circuits.N.operating.programs.active**      Shows the current active operating program on the device
**heating.circuits.N.temperature.levels**      Shows the lower and the upper limit of the supply temperature and provides commands to set the limits and the levels

**Comment by rogrun** [comment]
All basic-api-values should be added automatically.

For more debugging please email me the log in TRACE mode by typing in the OpenHAB console: 
`log:set TRACE org.smarthomej.binding.viessmann`

I'll take a look at this as soon as possible.

Here is my mail address: ronny.grun@t-online.de

**Comment by rogrun** [comment]
Thank you, I received your log and analyzed it.
> heating.boiler.temperature       Shows the set target temperature value of the boiler

This is the only feature provided by the API. Viessmann does not transfer the others.

> Also provides the command to set it
heating.circuits.N.temperature      Shows the value of the target temperature for circuit N
heating.circuits.N.operating.programs.active      Shows the current active operating program on the device
heating.circuits.N.temperature.levels      Shows the lower and the upper limit of the supply temperature and provides commands to set the limits and the levels

Viessmann does not support commands for these features. It only `Shows` the value or state.
