### ISSUE TITLE
TUYA Configurable Port Number

### ISSUE THREAD

**Issue by m-jarzebowski** [smarthomej/addons#472]
Hi All,
I would like to propose new configuration parameter, a port number. I know that current implementation relay on hardcoded 6668 port as it is common across all devices. The proposal is related to the security topic and network separation. The use case is to have all tuya/iot devices in a separated network without access to main network resources. For that purpose we need to be able to map devices behind a NAT. Mapping an incoming port to an external IP address requires also ability to configure it on the binding side. What do you think?
I'm ready to implement the change but maybe you will have some feedback.
Regards, MJ

**Comment by J-N-K** [comment]
I don't understand why you need to change the port when doing NAT, can you explain that a bit more?

**Comment by m-jarzebowski** [comment]
Sure. I have two separated networks let's say 192.168.5.0/24 (main) and network 192.168.6.0/24 (iot) both each of them is on separate hardware (two routers). So, the main network sees the iot network as one of the IPs from the pull - lets say 192.168.5.100 (iot_router). Also there is an OpenHab server getting IP let's say 192.168.5.200 (oh_server). The server is separated (in the separate network) for security reasons. Going next, oh_server needs to talk to some device let's say with IP 192.168.6.20 (device1). In this case as iot network is behind the NAT we need to configure that incoming traffic to iot network on concrete port will be directed to device1 on some port. So, whole communication chain looks like this:
oh_server (192.168.**5**.200) -> iot_router (192.168.**5**.100:6668) -> iot network (192.168.**6**.1) -> device1 (192.168.**6**.20:6668)
For now everything is ok. But when we add a second device in the iot network then we have no way to communicate with it as the add-on does not allow changing port number and we need to communicate  with the same IP (iot_router). Having ability to change the port for an item would allow to prepare configuration like this:
oh_server (192.168.**5**.200) -> iot_router (192.168.**5**.100:6668) -> iot network (192.168.**6**.1) -> device1 (192.168.**6**.20:6668)
oh_server (192.168.**5**.200) -> iot_router (192.168.**5**.100:1234) -> iot network (192.168.**6**.1) -> device2 (192.168.**6**.21:6668)
oh_server (192.168.**5**.200) -> iot_router (192.168.**5**.100:5678) -> iot network (192.168.**6**.1) -> device3 (192.168.**6**.22:6668)
and so one.
Hope it is now better explained.
