### ISSUE TITLE
[tuya] Device Missing Channels

### ISSUE THREAD

**Issue by jamesmelville** [smarthomej/addons#473]
I have a Pro Breeze Dehumidifier, which implement Tuya APIs and can be controlled by the Tuya Smart app (e.g. on/off, target humidity, fan speed etc.). This device is successfully detected by the Tuya binding, but the channels offered are only `anion` and `countdown_left`. This matches the API response (bar `fault`), shared below, so I assume the binding does not find the device in the database.

```
{
	"result": [
		{
			"active_time": 0,
			"biz_type": 0,
			"category": "cs",
			"create_time": 0,
			"icon": "smart/product_icon2/cs_1.png",
			"id": "0",
			"ip": "1.1.1.1",
			"lat": "0",
			"local_key": "0",
			"lon": "0",
			"model": "PB-20",
			"name": "Dehumidifier",
			"online": true,
			"owner_id": "0",
			"product_id": "0",
			"product_name": "Pro Breeze 30L Compressor Dehumidifier",
			"status": [
				{
					"code": "anion",
					"value": false
				},
				{
					"code": "fault",
					"value": 0
				},
				{
					"code": "countdown_left",
					"value": 0
				}
			],
			"sub": false,
			"time_zone": "+00:00",
			"uid": "0",
			"update_time": 0,
			"uuid": "0"
		}
	],
	"success": true,
	"t": 0,
	"tid": "0"
}
```

I see that the binding retrieves a schema from this URL - is this the database? https://raw.githubusercontent.com/Apollon77/ioBroker.tuya/master/lib/schema.json

I also found the "standard" instruction set for dehumidifiers https://developer.tuya.com/en/docs/iot/f?id=K9gf45ts0b8lz (my device doesn't implement all of them but it matches what's shown in Tuya Smart).

Can anyone share any pointers what I should do to get channels from the standard set into openHAB?

**Comment by J-N-K** [comment]
The schema is retrieved from an internal database or from the cloud. I'll check what is the case here.
