### ISSUE TITLE
Addon does not play nicely with tuya-mqtt

### ISSUE THREAD

**Issue by timo12357** [smarthomej/addons#474]
Hi
I just installed the addon an have tested it a few days with OH 3.4.2 I have tuya-mqtt running on the system and it seems like tuya-mqtt stops working with the addon active. Any more info on if this is a feature, bug or my misconfiguration?

**Comment by J-N-K** [comment]
It's a limitation of Tuya devices: they only support one local connection. If a second connection is opened, then the first connection is dropped. You can see the same if you cut off internet access and use the SmartLife app and tuya-mqtt or the binding. Only one will work.

**Comment by timo12357** [comment]
So it is either this add on or tuya-mqtt, but not both, then?

**Comment by J-N-K** [comment]
I don't use tuya-mqtt, but yes, I guess you have to choose.

**Comment by timo12357** [comment]
Life is.
