### ISSUE TITLE
Tuya PoolHeatpump Connection refused

### ISSUE THREAD

**Issue by juli-august** [smarthomej/addons#475]
Hi to all,

i tried to add a PoolHeatPump. It was discoverd and chanels were automticaly added.
But the device is offline any time.

Log shows:

`2023-03-26 23:44:25.488 [INFO ] [a.internal.handler.TuyaDeviceHandler] - Configuring IP address 'DeviceInfo{ip='192.168.130.11', version='3.3'}' for thing 'tuya:tuyaDevice:Tuya_PoolHeatPump'.
2023-03-26 23:44:25.576 [DEBUG] [nding.tuya.internal.local.TuyaDevice] - bf8ba95afbecd9f421h2iw: Failed to connect: Connection refused: /192.168.130.11:6668`

And this is my config:

`UID: tuya:tuyaDevice:Tuya_PoolHeatPump
label: Tuya Pool Heatpump
thingTypeUID: tuya:tuyaDevice
configuration:
  pollingInterval: 0
  protocol: "3.3"
  productId: KnyYbXw5HpOmnevV
  deviceId: bf8ba95afbecd9f421h2iw
  ip: 192.168.130.11
  localKey: 785286e13a374d24
location: Garten
channels:
  - id: temp_set
    channelTypeUID: tuya:number
    label: temp_set
    description: null
    configuration:
      dp: 2
      max: 40
      min: 8
  - id: temp_current
    channelTypeUID: tuya:number
    label: temp_current
    description: null
    configuration:
      dp: 3
      max: 990
      min: -200
  - id: switch
    channelTypeUID: tuya:switch
    label: switch
    description: null
    configuration:
      dp: 1
`

The device is at a different VLAN but at IOT.TUYA it is online.

Were is my mistake.

Best regards Julian

**Comment by juli-august** [comment]
I´m running on latest OpenHab Version on a Pi.
System is up to date.

**Comment by J-N-K** [comment]
Difficult to say. Did you try putting it on the same subnet? Tuya unfortunately is not Tuya and all devices are different. It could that is rejects packets which do not originate from the same subnet.

**Comment by juli-august** [comment]
Hi,

all is working now. Seams to be an issue with VLan.

Thanks
