### ISSUE TITLE
[Basic Profile - Round] After upgrade to OH 4.0.0.M2 item states are jumping up and down

### ISSUE THREAD

**Issue by LukasA83** [smarthomej/addons#477]
Yesterday I tried to upgrade to OH 4.0.0.M2. Every channel / item state using the round profile started to jump, see chart attached.  This also results in 100% CPU load. Using the default profile, everything was back to normal.

![Screenshot_20230417_061740_Chrome](https://user-images.githubusercontent.com/58861945/232377925-bf2376d4-9fb6-4c42-bd5f-dd17642682ff.png)

**Comment by J-N-K** [comment]
What type of item did you link to which binding/thing/channel?

**Comment by LukasA83** [comment]
Various bindings / channels, but see some examples below:

Binding / Thing: 
Kostal Plenticore (Solar inverter):
- Channels: 
![grafik](https://user-images.githubusercontent.com/58861945/232393103-e7ab4172-b247-418c-a924-f17080eb57ec.png)
![grafik](https://user-images.githubusercontent.com/58861945/232393325-d2b93150-261f-47a8-8d64-195297f0e785.png)
![grafik](https://user-images.githubusercontent.com/58861945/232394032-72086b5d-0385-49af-8105-0d4808b8fc75.png)
The last one is a consumption per day measurement, which physically can only increase, not decrease, but during that time the value dropped lower (due to this behaviour, round is set to 2 digits, 9.74 becomes 9.7 then 9.74 again):
![grafik](https://user-images.githubusercontent.com/58861945/232394238-afe23211-0f48-405e-938f-300154f2fa1b.png)


SmartMeter
Channels:
![grafik](https://user-images.githubusercontent.com/58861945/232393578-d2e61277-ead3-49b1-9980-d026aa64563d.png)

**Comment by J-N-K** [comment]
See https://github.com/smarthomej/addons/pull/95#discussion_r1168337321
