### ISSUE TITLE
Tuya binding compile failure in 4.0.x Branch

### ISSUE THREAD

**Issue by rlarranaga** [smarthomej/addons#480]
Hello,
I upgraded my OH install to 4.0 M2. I had the smarthomej repository installed through the UI.
The smarthomej/tuya binding disappeared, so i thought to compile it manually.

When i compile, one of the test fails with the following error:

```
[ERROR] Failures: 
[ERROR]   ConversionUtilTest.hexColorDecodeTestOld:46 expected: <240,100,50> but was: <240,100,50.196>
[INFO] 
[ERROR] Tests run: 14, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
```
Any ideas on how can is this a known issue in the 4.0.x branch?

Thanks

**Comment by J-N-K** [comment]
Thanks for reporting. This is related to a changeset that was merged this morning. I'll provide a fix tomorrow.

**Comment by rlarranaga** [comment]
Should third party add-on repo work on 4.0?

Thanks!

**Comment by J-N-K** [comment]
Use `https://download.smarthomej.org/addons-snapshot.json`, but don't forget to switch back to the original URL after release.

**Comment by rlarranaga** [comment]
Will not forget, thanks,
The json service is not working for me, it appears the community marketplace its not loading properly for some reason. i will wait for the fix and see if i can recompile

**Comment by J-N-K** [comment]
That's another issue in openhab-core. Can you send me the the `<userdata>/jsondb/org.openhab.jsonaddonservice.json` and `org.openhab.marketplace.json` files to github@klug.nrw?

**Comment by rlarranaga** [comment]
Just did.
Thanks

**Comment by rlarranaga** [comment]
Hi,

i was able to compile the tuya binding with the last fixes.

However, i realize i also need smarthomej commons, and that fails compiling with the following error:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.2.0:jar (attach-javadocs) on project org.smarthomej.commons: MavenReportException: Error while generating Javadoc: Unable to find javadoc command: The environment variable JAVA_HOME is not correctly set. -> [Help 1]`


Any idea why?

Thanks

**Comment by rlarranaga** [comment]
Hey,

Is there any other way I could go to try and get this binding working in 4.0M2? 

Thanks for your help

**Comment by rlarranaga** [comment]
Hello @J-N-K ,

I realized that i only sent you one of the requested files when you asked. I just sent both of them to the email address you posted before.

Let me know if you got them.

Thanks!

**Comment by rlarranaga** [comment]
Hello @J-N-K ,
I managed to compile org.smarthomej.commons by skipping the javadocs section.

My devices are all initialized now, however, none of them works (They all show as offline). The only thing that shows as online is the Cloud Project.

Looking into functionality, the devices are recognized (If i delete a device and scan , the device is automatically detected), and they definitely send some packets, as shown below:

`
15:40:08.939 [DEBUG] [a.internal.local.handlers.TuyaDecoder] - udpListener: Received MessageWrapper{commandType=UDP_NEW, content='DiscoveryMessage{ip='XXX.XXX.XXX.XXX', deviceId='BBBBBBBBBBBBB', active=2, ability=0, mode=0, encrypt=true, productKey='AAAAAAAAAAAAAAAA, version='3.3', token= true, wf_cfg=true}'}`

I get one of those messages for each device i have on connected. However, when  Openhab tries to connect, there is no response:

`15:40:10.977 [DEBUG] [inding.tuya.internal.local.TuyaDevice] - BBBBBBBBBBBBBBBBB/XXX.XXX.XXX.XXX:6668: Failed to connect: connection timed out: /XXX.XXX.XXX.XXX:6668
`
There is also one of those messages for every device connected.

Any insights on what else can i check?

Thanks!

**Comment by rlarranaga** [comment]
Never mind. Power cycling all lights resolved the issue, which is a bit strange, since they were all responsive through the app (Even though i was not trying to use them through the app and through OpenHAB simultaneously.

I will wait for the repository fix, and the core fix you mentioned for OpenHAB. Please let me know if you need any more info regarding those.

Thanks!
