### ISSUE TITLE
How to install the Addon

### ISSUE THREAD

**Issue by christianmerges** [smarthomej/addons#485]
Hi,

i have a virgin openHAB v4 Server in docker and would like to install this addon: [org.smarthomej.binding.tuya](https://github.com/smarthomej/addons/tree/3.2.x/bundles/org.smarthomej.binding.tuya)

I have no idea how I can do that. I even didn't found something on the internet, because i assume it's to simple, but I don't know how. When i place the files in my /openhab/addons directory, the sotware doesn't find them. I changeowned the directory before starting the conainer and made sure the container is using same UID/GID as i chowned.

**Comment by J-N-K** [comment]
Use the JSON 3rd Party Add-on service as described on https://github.com/smarthomej/addons (scroll down). For openHAB 4 use `https://download.smarthomej.org/addons-snapshot.json`as URL.

**Comment by christianmerges** [comment]
Thank u for ur fast replay. Can i kindly ask u where exectly to put the "https://download.smarthomej.org/addons-snapshot.json" URL?

**Comment by J-N-K** [comment]
In the UI, "Settings" on the right column, "JSON 3rd Party Add-on service" (JSON Drittanbieter Add-ons" in German).
