### ISSUE TITLE
[Viessmann] After initial install on OH4 unable to crete/dicover things

### ISSUE THREAD

**Issue by JueBag** [smarthomej/addons#513]
After the initial install of the Smarthome/J Viessmann binding on OH4 no things could be created nor discovered. 
The same was reported by another community member ( [Forum Thread ](https://community.openhab.org/t/smarthome-j-viessmann-binding-for-4-0-x/148134) ) plus an unconfirmed one.
Removing the binding and reinstall solved the problem.

**Comment by rogrun** [comment]
@J-N-K I think this issue is closed via #514
