### ISSUE TITLE
Problems in OH4

### ISSUE THREAD

**Issue by matzeeg3** [smarthomej/addons#518]
Hi i did the update to OH4 and after that i see:
smarthomej/Math
smarthomej/tuya
as installed in the gui. however in openhab-cli i see:
`feature:list | grep smarthomej
smarthomej-transformation-math                    │ 3.2.16           │          │ Uninstalled │ org.smarthomej.transform.math-3.2.16       │ Math Transformation
smarthomej-binding-tuya                           │ 3.2.16           │          │ Uninstalled │ org.smarthomej.binding.tuya-3.2.16         │ Tuya Binding
`
how can i update it to version 4? thanks
kind regards
matze

**Comment by gbravery** [comment]
Just to report what I just found - I was having the same problem with smarthomej/tuya (i.e. I've gone to OH4, the binding isn't working, gui is reporting 4 installed, backend is showing an obviously 3.4 kar file).

I simply removed the addon (using the GUI), and then re-add it (also using GUI). 
The file system kar file version changed to 4 and Tuya kicked straight back into life.

FWIW, the front page here does indicate this is the process - it just seems a bit broken that one of the locations (the addon screen itself) is lying about what is installed!

Also - I also didn't loose anything - everything just works as it did before.

**Comment by matzeeg3** [comment]
i am not able to remove the addon in the gui it say installation failed. i know i hit uninstall but it says installation failed
same for the math binding

**Comment by gbravery** [comment]
My ability to help further is probably exhausted then (since mine "just worked").

The only other thing I can do is confirm that I clicked "Remove" when at this URL:
http://<host>:<port>/settings/addons/json:org-smarthome-binding-tuya

At which point I could now click the "Install" button that now showed (as it had uninstalled).

If the uninstall is failing, it's probably time to hit the logs :-(

Sorry,
G

**Comment by matzeeg3** [comment]
i recive that:
![image](https://github.com/smarthomej/addons/assets/16683343/ceedfa87-54be-4edf-bf0e-0c30367645ed)
and i don´t find anything in the logs :(

**Comment by J-N-K** [comment]
The easiest fix is probably to shutdown openHAB, edit the `org.openhab.jsonaddonservice.json` file (in `<userdata>/jsondb` (on most Debian-like systems this is `/var/lib/openhab/jsondb`) to contain only `{}` and delete the `<userdata>/marketplace` directory. After that you should be able to install from UI.

**Comment by matzeeg3** [comment]
> The easiest fix is probably to shutdown openHAB, edit the `org.openhab.jsonaddonservice.json` file (in `<userdata>/jsondb` (on most Debian-like systems this is `/var/lib/openhab/jsondb`) to contain only `{}` and delete the `<userdata>/marketplace` directory. After that you should be able to install from UI.

Thanks J-N-K that helpt me out in this case.
greetings to the ruhrpot.
Kind regards
matze
