### ISSUE TITLE
Math transformation services disappeared

### ISSUE THREAD

**Issue by clinique** [smarthomej/addons#530]
I'm on openHAB 4.1.0 Build #3687.

SmarthomeJ is present in the tier json extension : 
![image](https://github.com/smarthomej/addons/assets/3328789/2717d9d4-4a71-4d6a-a805-f6ecf71aa120)

After an upgrade this morning apparently I'm not able to access this service, it's no longer in the list of installable services :
![image](https://github.com/smarthomej/addons/assets/3328789/eeed6da1-ec4c-4127-95f0-0925c2da2839)

**Comment by J-N-K** [comment]
Server issue. Fixed.
