### ISSUE TITLE
Commands not effecting Tuya Smart Plug

### ISSUE THREAD

**Issue by TrekGIneer22** [smarthomej/addons#536]
I have some Tuya plugs and OH4 and was able to use your Tuya Binding to get them connected through the Tuya website but I cant use openHAB to change their state.  If I trigger them from the Smart Life app openHAB can see and display their state correctly but if I try to use openHAB to trigger them nothing happens, changes are not communicated to the website or the plug itself.

**Comment by J-N-K** [comment]
Did you solve your issues?

**Comment by TrekGIneer22** [comment]
oh actually no I didn't, I was thinking this was for something else.  Thanks for following up so I could notice

**Comment by JasonMask** [comment]
hi,

i belief to have the same issue.  unfortunatally the logs do not provide many helpfull information, exept of the udp listener logging an unexpected end of input and the devices going on and offline once in a while. also the device things pretending to have sent the command but no action follows. also the plugin seams incapable to fetch the current state from the devices

im running openhabian 1.9beta/openhab 4.1.1 on an raspberry 5
i have one tuya device setup with the smart app and one other with tuya app. both could be found using discovery but could not detect their own local ip adress. once i defined these manually the devices are listed as being online (most of the time)

is there anything one could do to help you debugging the issue?

update: i finally gave up and enabled control through mqtt by flashing my devices with OpenBK as described here: https://www.elektroda.com/rtvforum/topic4020803.html
hope this is a help for anyone who just want control over the device and doesn´t need a tuya app functionality

**Comment by alexgug** [comment]
Hi, 

I have the same issue; I posted it on the Openhab Community, but here it is : [https://community.openhab.org/t/smarthome-j-tuya-binding-for-openhab-4/147193/56?u=alexandre_guglielmin](url)

Hi Everyone, 

I don't understand why my dimmer switch (Gosund) don't work.
I can switch it ON/OFF from Openhab and the physical button.
I can use the physical dimmer and it modified the bright_value in Openhab.
But when I modify the bright_value in Openhab, nothing happen.
I have 2 of them, and it's exactly the same behavior for both.

Each Things have been added by the Binding, using the scan button.
Here's the configuration of the channel : 
![image](https://github.com/smarthomej/addons/assets/74321841/55a2cbc3-1679-44ee-8ff2-adc78637d42a)

The DPs have been validated using the Tuya Platform and the manual method described here : https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html#_8-find-your-data-point

I have nothing in the logs except the value changed in the events.log : 
```
2024-02-28 08:08:47.530 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'Bar_Light_bright_value' received command 59
2024-02-28 08:08:47.531 [INFO ] [penhab.event.ItemStatePredictedEvent] - Item 'Bar_Light_bright_value' predicted to become 59
2024-02-28 08:08:47.532 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Bar_Light_bright_value' changed from 36 to 59
```
I suspected a missconfiguration between the item, the min/max value, the fact that it's a dimmer, etc...
But I tried a lot of configuration and find nothing...
Can someone help me ?

**Comment by alexgug** [comment]
Here's the TRACE log I have from Openhab;
Everything seems to work, I can do an update from the Smart Life app, fom Tuya Platform, from Postman... 
But the "bright_value" command from Openhab just didn't work. 

```
[a.internal.local.handlers.TuyaEncoder] - [DEVICE_ID]/[IP]:6668: Sending CONTROL, payload {devId=[DEVICE_ID], uid=[DEVICE_ID], t=1709576826, dps={1=true, 3=89}, gwId=[DEVICE_ID]}

[a.internal.local.handlers.TuyaDecoder] - [DEVICE_ID]/[IP]:6668: Received MessageWrapper{commandType=CONTROL, content='[B@2737708e'}
```

**Comment by TrekGIneer22** [comment]
boop to de stale?
