### ISSUE TITLE
Device with 3.5 protocole

### ISSUE THREAD

**Issue by xyz-09** [smarthomej/addons#579]
My device is switching offline/offline on each protocole version.
From json I know it uses protocole 3.5

On trace Level

```
19:09:49.567 [TRACE] [a.internal.local.handlers.TuyaDecoder] - Did not receive enough bytes from 'udpListener', exiting early

19:09:50.319 [DEBUG] [nal.local.handlers.TuyaMessageHandler] - bfbb1b76df3362a9e5pkns/local.controler.IP:6668: Connection terminated.

19:09:50.319 [DEBUG] [ya.internal.handler.TuyaDeviceHandler] - [tuya:ir-controller] stop ir learning
```

**Comment by J-N-K** [comment]
Currently protocol 3.5 is not supported.

**Comment by J-N-K** [comment]
https://github.com/jasonacox/tinytuya/discussions/260

This needs to be implemented. However, it's hard to do without a device. Do you know how to use Wireshark and do you use the SmartLife app?

**Comment by xyz-09** [comment]
https://github.com/jasonacox/tinytuya/discussions/260 

I ran this script to confirm that I have a proper connection with the device. 

Yes, I use the SmartLife app, but I have never used Wireshark.

I installed Wireshark few minutes ago, but I don't see the IP address to which the device is connected in the monitoring list. 

When I scanned my connection by running the script above again, I still don't see any communication with the device, even though the Python script prints a response - so connection exist.

I do not know how may i help better :thinking:

**Comment by xyz-09** [comment]
This Python repository has partial support for protocol 3.5 implemented.

https://github.com/jasonacox/tinytuya

But it doesn't support my device.

**Comment by xyz-09** [comment]
> But it doesn't support my device.

I am correcting my entry - the device actually works on protocol 3.5.

So there is a starting point to implement protocol 3.5 :smile:

**Comment by J-N-K** [comment]
Keep open
