### ISSUE TITLE
Openhab 4.3.x support

### ISSUE THREAD

**Issue by ThaDaVos** [smarthomej/addons#585]
It seems SmarthomeJ addons aren't listed without changing the setting for "Show (possibly) incompatible addons" to `true` in the "Addons Management" settings page when running:
```
openHAB 4.3.0
Build #4181
```

Is there any specific reason for this? Or do we just need to wait for the next builds which should be 4.3.x compatible?
The 4.2.x ones still seem to work though

**Comment by J-N-K** [comment]
I just forgot to add it. Should work now.
