### ISSUE TITLE
[Viessmann] New errors since 3rd Oct. Change in API?

### ISSUE THREAD

**Issue by JueBag** [smarthomej/addons#594]
Since 3rd Oct SmarhomeJ/ Viessmann reports errors like:
`2024-10-06 15:11:19.200 [WARN ] [ernal.handler.ViessmannBridgeHandler] - Parsing Viessmann response fails: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 15 column 21 path $.data[0].properties.entries.value`

The reported API-change with due date 19th Sep migth be the cause.

See also:[openHAB forum](https://community.openhab.org/t/smarthome-j-viessmann-binding-for-4-0-x/148134/24)

**Comment by rogrun** [comment]
This issue is fixed in this PR #593 
@J-N-K what do we need for merging? should I update 4.3.x and you cherrypick this commit?

**Comment by JueBag** [comment]
Did an Update of my complete system to have:
`315 │ Active │  80 │ 4.2.0                 │ SmartHome/J Add-ons :: Bundles :: Viessmann Binding`
 Now the heating device remains initilazing and the log shows:
`2024-10-07 11:33:47.123 [WARN ] [ernal.handler.ViessmannBridgeHandler] - Parsing Viessmann response fails: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 15 column 21 path $.data[0].properties.entries.value`

**Comment by MaTr74** [comment]
> Did an Update of my complete system to have: `315 │ Active │ 80 │ 4.2.0 │ SmartHome/J Add-ons :: Bundles :: Viessmann Binding` Now the heating device remains initilazing and the log shows: `2024-10-07 11:33:47.123 [WARN ] [ernal.handler.ViessmannBridgeHandler] - Parsing Viessmann response fails: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 15 column 21 path $.data[0].properties.entries.value`

Same for me!

**Comment by rogrun** [comment]
@J-N-K can you please publish a new release?

**Comment by MaTr74** [comment]
Maybe @J-N-K is on vacation? Can we do something else to get the fixed addon?

**Comment by J-N-K** [comment]
I'm currently very busy with real life issues. I'll try to merge both other fixes later today and release a new Version either today or tomorrow.

**Comment by MaTr74** [comment]
@J-N-K Thank you very much! No pressure, real life is much more important.

**Comment by J-N-K** [comment]
I have uploaded the snapshot, please try if that works (URL is the same). I have some issues with the release build.

**Comment by JueBag** [comment]
Did a Uninstall-Insrall via MainUi. The error remains the same. Am I doing something wrong.
The file has a date of today at  15:25.

**Comment by rogrun** [comment]
I did the same thing. After the reinstallation, version 4.2.0 was installed.

When I open the URL (https://download.smarthomej.org/addons.json) and search for the KAR file, I get the correct version 4.2.1.202410131143 
I put it manually in the addons folder.

**Comment by JueBag** [comment]
In this case I am doing something completly wrong! The returned json-string from the posted URL has no match with "4.2.1.202410131143".
No clue ATM.

**Comment by J-N-K** [comment]
That's a drawback in the was openHAB handles JSON addons. It's necessary to regresh the list of remote addons,either by waiting (at most) 15 minutes after uninstallation or rebooting. Otherwise the cached add-on list will be used (which contains the previously installed Version).

**Comment by JueBag** [comment]
Uninstall-Reboot-Install did the trick!
Thanks for your effort and the pointer on WhowToDoIt.
@rogrun Thanks for your support as well.

**Comment by MaTr74** [comment]
Will the new version available for OH 4.1.3 too? Due to another problem I can't update OH to 4.2.x.

**Comment by MaTr74** [comment]
I've just reinstalled the plugin within OH 4.1.3 and it's working gain. Thank you for your work!

**Comment by skladd** [comment]
@J-N-K Could it be the fixed version is not yet released for OH 4.3?

**Comment by rogrun** [comment]
@J-N-K I checked the version in the [addons.json](https://download.smarthomej.org/addons.json) The included KAR-File does not contain the FIX. Can you please compile a new version or put this version [org.smarthomej.binding.viessmann-4.3.0-SNAPSHOT.kar](https://github.com/rogrun/addons/releases/download/viessmann-4.3.0/org.smarthomej.binding.viessmann-4.3.0-SNAPSHOT.kar) on your server?
