### ISSUE TITLE
[feature request] please add support for receiving

### ISSUE THREAD

**Issue by WiredLife** [smarthomej/addons#91]
would be very nice if you can add support for receiving
i like to have a thing which listen on a udp port and give the received input to a string item
thank you very much!

**Comment by J-N-K** [comment]
You can try to download

https://jenkins.smarthomej.org/job/SmartHomeJ%20PR%20Builds/122/artifact/bundles/org.smarthomej.binding.tcpudp/target/org.smarthomej.binding.tcpudp-3.1.2-SNAPSHOT.jar

and 

https://jenkins.smarthomej.org/job/SmartHomeJ%20PR%20Builds/122/artifact/bundles/org.smarthomej.commons/target/org.smarthomej.commons-3.1.2-SNAPSHOT.jar

The documentation can be found here:

https://github.com/J-N-K/addons/tree/tcpudp-receiver/bundles/org.smarthomej.binding.tcpudp

If there is something unclear, please feel free to ask.

**Comment by WiredLife** [comment]
Can you help me to create the things file? I have no clue without an example how it looks like.
And is it recommended to upgrade to OH 3.1?

**Comment by J-N-K** [comment]
I have added your last example to the documentation. Thanks for testing.
